In [32]:
import numpy as np
A=np.diag([1,-1,-1])

In [33]:
T = A.transpose()
print(T)
E=A.dot(T)
E

[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [126]:
C=np.triu([[1,0,0],[6,-1,0],[3,6,-1]],0)

In [127]:
B = C.transpose()
C.dot(B)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [130]:
F=np.tril([[-1,4,9],[0,1,5],[0,0,-1]],0)
F

array([[-1,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [131]:
D = F.transpose()
F.dot(D)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [132]:
H=np.array([[-1/3,2/3,2/3],[2/3,-1/3,2/3],[2/3,2/3,-1/3]])

In [133]:
np.linalg.det(H)

1.0

In [134]:
m = np.array([[2, 2],
              [1, 3]])

In [135]:
x,z=np.linalg.eig(m)

In [136]:
for i in range(len(x)):
    print("Собственное значение " + str(x[i]))
    print("соответствующий ему собственный вектор " + str(z[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]
